### ISSUE TITLE
TypeError in FutureHistoryBeam

### ISSUE THREAD

**Issue by yunhak0** [mateuszjurewicz/set-interdependence-transformer#1]
https://github.com/mateuszjurewicz/set-interdependence-transformer/blob/399d93b9beea84a9ae3332ab5caf04a67decb1fb/models.py#L1052

Hello @mateuszjurewicz 

Thank you for sharing amazing work!

I have a question about FutureHistoryBeam.
When I ran the 'synthetic.py' file, I faced an error related to the index of candidates.

*****
Exception has occurred: TypeError
list indices must be integers or slices, not float
*****

When calculating 'beam_ix', the code divided the index into batch sizes (the result is float).
However, the 'beam_ix' (float) is used to index for 'prev_candidates'.
Additionally, the prev_candidates is [[]] at the initial stage. So, it cannot be 'prev_candidates[b_ix]'.

I think this issue is not only for 'synthetic' but also for all other processes.

Could you please look into it?

**Comment by mateuszjurewicz** [comment]
Hello @yunhak0 

Thank you for your kind words! 

Could you let me know which python version you're using and attach the full experiment config (for both model and the run)?

**Comment by yunhak0** [comment]
Hello @mateuszjurewicz 

Thank you for the prompt feedback!
My Python version is 3.9.12 and I used the default experiment config in your repo.

[synthetic.json](https://github.com/mateuszjurewicz/set-interdependence-transformer/blob/399d93b9beea84a9ae3332ab5caf04a67decb1fb/model_configs/synthetic.json)
[synthetic.py](https://github.com/mateuszjurewicz/set-interdependence-transformer/blob/399d93b9beea84a9ae3332ab5caf04a67decb1fb/synthetic.py)
[models.py](https://github.com/mateuszjurewicz/set-interdependence-transformer/blob/399d93b9beea84a9ae3332ab5caf04a67decb1fb/models.py)

**Comment by mateuszjurewicz** [comment]
Thank you for a quick response!

I'm having real trouble reproducing the bug, but I suspect it's an issue with library versions. In retrospect I should've used the poetry package manager to make sure setting up the exact same virtual environment will be easy. 

Could I ask you to try running it with Python `3.6.5` and double-checking that all your libraries match these versions:

```
absl-py==0.8.1
aif360==0.2.3
appnope==0.1.0
astor==0.8.0
astunparse==1.6.3
attrdict==2.0.1
attrs==19.3.0
backcall==0.1.0
bcolz==1.2.1
bleach==3.1.0
blis==0.4.1
bravado==10.6.0
bravado-core==5.16.1
cachetools==3.1.1
catalogue==1.0.0
certifi==2019.9.11
chardet==3.0.4
click==7.1.1
colorama==0.4.3
cycler==0.10.0
cymem==2.0.3
dataclasses==0.8
datasets==1.5.0
de-core-news-sm==2.2.5
decorator==4.4.1
defusedxml==0.6.0
dill==0.3.4
docopt==0.6.2
en-core-web-sm==2.2.5
entrypoints==0.3
filelock==3.0.12
fsspec==2021.8.1
future==0.18.2
gast==0.3.3
gdown==3.12.2
gitdb==4.0.2
GitPython==3.1.0
google-auth==1.7.0
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
graphviz==0.13.2
grpcio==1.25.0
h5py==2.10.0
hashfs==0.7.2
hmmlearn==0.2.3
huggingface-hub==0.0.16
idna==2.8
imageio==2.6.1
importlib-metadata==0.23
iniconfig==1.1.1
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.1
json5==0.8.5
jsonpickle==1.3
jsonpointer==2.0
jsonref==0.2
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
jupyterlab==1.2.2
jupyterlab-server==1.0.6
Keras==2.4.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.1.2
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
monotonic==1.5
more-itertools==7.2.0
msgpack==1.0.0
msgpack-python==0.5.6
multiprocess==0.70.12.2
munch==2.5.0
murmurhash==1.0.2
nbconvert==5.6.1
nbformat==4.4.0
neptune-client==0.4.108
neptune-contrib==0.17.0
networkx==2.4
nltk==3.4.5
notebook==6.0.2
numpy==1.17.3
oauthlib==3.1.0
opencv-python==4.1.2.30
opt-einsum==3.1.0
packaging==21.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.1
plac==1.1.3
pluggy==0.13.1
preshed==3.0.2
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.10.0
psycopg2==2.8.4
ptyprocess==0.6.0
py==1.9.0
py-cpuinfo==5.0.0
py3nvml==0.2.5
pyaml==20.3.1
pyarrow==5.0.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
pydot==1.4.1
Pygments==2.4.2
PyJWT==1.7.1
pymongo==3.10.1
pyparsing==2.4.4
pyrsistent==0.15.5
PySocks==1.7.1
pytest==6.1.2
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==18.1.0
qtconsole==4.5.5
regex==2021.8.28
requests==2.22.0
requests-oauthlib==1.3.0
rfc3987==1.3.8
rsa==4.0
sacred==0.8.1
sacremoses==0.0.45
scikit-image==0.16.2
scikit-learn==0.22.1
scikit-optimize==0.7.4
scikit-plot==0.3.7
scipy==1.3.3
seaborn==0.10.0
Send2Trash==1.5.0
sentencepiece==0.1.86
simplejson==3.17.0
six==1.13.0
sklearn==0.0
smmap==3.0.1
spacy==2.2.4
srsly==1.0.2
strict-rfc3339==0.7
swagger-spec-validator==2.5.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.0
tensorflow-addons==0.8.3
tensorflow-estimator==2.3.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.4
thinc==7.4.0
tinydb==3.15.2
tinydb-serialization==1.0.4
tokenizers==0.9.2
toml==0.10.2
torch==1.4.0
torchsummary==1.5.1
torchtext==0.6.0
torchvision==0.5.0
tornado==6.0.3
tqdm==4.46.0
traitlets==4.3.3
transformers==3.4.0
typeguard==2.7.1
typing-extensions==3.7.4.1
urllib3==1.25.6
wasabi==0.6.0
wcwidth==0.1.7
webcolors==1.11.1
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
xmltodict==0.12.0
xxhash==2.0.2
zipp==0.6.0

```

**Comment by yunhak0** [comment]
Hi @mateuszjurewicz 

I tried to install python 3.6.5 and requirements.txt using pip as below.
However, I excluded de-core-news-sm==2.2.5, en-core-web-sm==2.2.5 due to error.
Additionally, I loosen the scipy version (>=1.3.3) due to conflict.

# Cause 

Casting [related issue](https://github.com/pytorch/pytorch/issues/5411#issue-300316501)

```
beam_ix = nbest_ix / prob.size(1) 
# Original Environment: tensor([0], device='cuda:0')
# My Environment: tensor([0.0625], device='cuda:0')
```

So, if the code is changed, it is fixed.

```
beam_ix = nbest_ix // prob.size(1) 
```

-----------------

# Environment

```
conda create --no-default-packages -n py36 python=3.6.5
pip install requirements.txt
```

## Install Error
ERROR: Could not find a version that satisfies the requirement de-core-news-sm==2.2.5 (from versions: none)
ERROR: No matching distribution found for de-core-news-sm==2.2.5

ERROR: Could not find a version that satisfies the requirement en-core-web-sm==2.2.5 (from versions: none)
ERROR: No matching distribution found for en-core-web-sm==2.2.5

## Conflict
The conflict is caused by:
    The user requested scipy==1.3.3
    aif360 0.2.3 depends on scipy
    hmmlearn 0.2.3 depends on scipy>=0.15
    keras 2.4.0 depends on scipy>=0.14
    scikit-image 0.16.2 depends on scipy>=0.19.0
    scikit-learn 0.22.1 depends on scipy>=0.17.0
    scikit-optimize 0.7.4 depends on scipy>=0.18.0
    scikit-plot 0.3.7 depends on scipy>=0.9
    seaborn 0.10.0 depends on scipy>=1.0.1
    tensorflow 2.3.0 depends on scipy==1.4.1

## requirements.txt

absl-py==0.8.1
aif360==0.2.3
appnope==0.1.0
astor==0.8.0
astunparse==1.6.3
attrdict==2.0.1
attrs==19.3.0
backcall==0.1.0
bcolz==1.2.1
bleach==3.1.0
blis==0.4.1
bravado==10.6.0
bravado-core==5.16.1
cachetools==3.1.1
catalogue==1.0.0
certifi==2019.9.11
chardet==3.0.4
click==7.1.1
colorama==0.4.3
cycler==0.10.0
cymem==2.0.3
dataclasses==0.8
datasets==1.5.0
#de-core-news-sm==2.2.5
decorator==4.4.1
defusedxml==0.6.0
dill==0.3.4
docopt==0.6.2
#en-core-web-sm==2.2.5
entrypoints==0.3
filelock==3.0.12
fsspec==2021.8.1
future==0.18.2
gast==0.3.3
gdown==3.12.2
gitdb==4.0.2
GitPython==3.1.0
google-auth==1.7.0
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
graphviz==0.13.2
grpcio==1.25.0
h5py==2.10.0
hashfs==0.7.2
hmmlearn==0.2.3
huggingface-hub==0.0.16
idna==2.8
imageio==2.6.1
importlib-metadata==0.23
iniconfig==1.1.1
ipykernel==5.1.3
ipython==7.9.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
joblib==0.14.1
json5==0.8.5
jsonpickle==1.3
jsonpointer==2.0
jsonref==0.2
jsonschema==3.1.1
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
jupyterlab==1.2.2
jupyterlab-server==1.0.6
Keras==2.4.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.1.2
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
monotonic==1.5
more-itertools==7.2.0
msgpack==1.0.0
msgpack-python==0.5.6
multiprocess==0.70.12.2
munch==2.5.0
murmurhash==1.0.2
nbconvert==5.6.1
nbformat==4.4.0
neptune-client==0.4.108
neptune-contrib==0.17.0
networkx==2.4
nltk==3.4.5
notebook==6.0.2
numpy==1.17.3
oauthlib==3.1.0
opencv-python==4.1.2.30
opt-einsum==3.1.0
packaging==21.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.1
plac==1.1.3
pluggy==0.13.1
preshed==3.0.2
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.10.0
psycopg2==2.8.4
ptyprocess==0.6.0
py==1.9.0
py-cpuinfo==5.0.0
py3nvml==0.2.5
pyaml==20.3.1
pyarrow==5.0.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
pydot==1.4.1
Pygments==2.4.2
PyJWT==1.7.1
pymongo==3.10.1
pyparsing==2.4.4
pyrsistent==0.15.5
PySocks==1.7.1
pytest==6.1.2
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==18.1.0
qtconsole==4.5.5
regex==2021.8.28
requests==2.22.0
requests-oauthlib==1.3.0
rfc3987==1.3.8
rsa==4.0
sacred==0.8.1
sacremoses==0.0.45
scikit-image==0.16.2
scikit-learn==0.22.1
scikit-optimize==0.7.4
scikit-plot==0.3.7
scipy>=1.3.3
seaborn==0.10.0
Send2Trash==1.5.0
sentencepiece==0.1.86
simplejson==3.17.0
six==1.13.0
sklearn==0.0
smmap==3.0.1
spacy==2.2.4
srsly==1.0.2
strict-rfc3339==0.7
swagger-spec-validator==2.5.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow==2.3.0
tensorflow-addons==0.8.3
tensorflow-estimator==2.3.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.4
thinc==7.4.0
tinydb==3.15.2
tinydb-serialization==1.0.4
tokenizers==0.9.2
toml==0.10.2
torch==1.4.0
torchsummary==1.5.1
torchtext==0.6.0
torchvision==0.5.0
tornado==6.0.3
tqdm==4.46.0
traitlets==4.3.3
transformers==3.4.0
typeguard==2.7.1
typing-extensions==3.7.4.1
urllib3==1.25.6
wasabi==0.6.0
wcwidth==0.1.7
webcolors==1.11.1
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wrapt==1.11.2
xmltodict==0.12.0
xxhash==2.0.2
zipp==0.6.0

**Comment by mateuszjurewicz** [comment]
Awesome, thank you @yunhak0!
